export * from './Footer/Footer.tsx'
export * from './NavBar/NavBar.tsx'
export * from './CardTurno/CardTurno.tsx'
export * from './CardEvent/CardEvent.tsx'
export * from './ImgCarousel/ImgCarusel.tsx'
export * from './CardEvent/CardEventNoDelete.tsx'
export * from './ImgCarousel/ImgCarouselBig.tsx'